#!/usr/bin/env python3
# Regenerate sitemap.xml from what is actually on disk.
#
#   tools/gen-sitemap.py                      # rewrite sitemap.xml in place
#   tools/gen-sitemap.py --check              # exit 1 if the file is stale
#
# Why a generator and not a hand-edited file: the current sitemap.xml is
# hand-written, and every hand-written sitemap on earth drifts from the site it
# describes. This one derives all three of its moving parts:
#
#   * which URLs go in   - every *.html at the repo root whose <meta name=
#                          "robots"> does NOT contain "noindex", minus
#                          admin.html, which is deliberately unadvertised.
#                          Submitting a noindex URL earns a permanent Search
#                          Console warning; deriving the list makes that
#                          impossible to get wrong by hand.
#   * <lastmod>          - the file's last commit date from git, falling back
#                          to its mtime outside a checkout. Google only uses
#                          lastmod when it finds it consistently accurate, so
#                          it must never be "today" for a file nobody touched.
#   * <image:image>      - every <img> on the homepage that carries a non-empty
#                          alt, i.e. content photography, not the logo and not
#                          the decorative scrims. Google Images is a real
#                          channel for a wedding studio and these 24 files are
#                          otherwise reachable only by rendering the page.
#                          Only <image:loc> is emitted: Google dropped support
#                          for image:caption, image:title, image:license and
#                          image:geo_location in 2022 and ignores them now.
#
# No claim here is invented - every URL and every image already exists in the
# repo, and every date comes from version control.

import os, re, subprocess, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'sitemap.xml')

# The origin is read from the homepage's own <link rel="canonical"> rather than
# hard-coded, so this script cannot re-introduce the SITE_URL placeholder after
# tools/set-site-url.sh has already run - and cannot invent a domain either. If
# the canonical is still the placeholder, so is the sitemap, and check.sh keeps
# failing exactly as it is meant to.
def site_origin():
    src = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
    m = re.search(r'<link rel="canonical" href="([^"]+)"', src)
    if not m:
        sys.exit('gen-sitemap: no <link rel="canonical"> in index.html')
    return m.group(1).rstrip('/')

SKIP = {'admin.html'}

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/gen-sitemap.py - do not hand-edit; rerun the script.

     accessibility.html, privacy.html and terms.html are absent because they
     carry <meta name="robots" content="noindex, follow">; the generator reads
     that tag rather than trusting a list. The footer links keep them reachable
     and "follow" preserves link flow.

     One further page is deliberately excluded and is not named here: this file
     is public, and a comment pointing at a private path is an invitation. The
     generator's own exclusion list is the place to read it.

     The image entries below are the homepage's content photographs, i.e.
     every img element with a non-empty alt. Only the loc child is emitted -
     Google deprecated caption, title, licence and geo_location in 2022. -->
"""


def git_date(path):
    try:
        d = subprocess.run(['git', '-C', ROOT, 'log', '-1', '--format=%cs', '--', path],
                           capture_output=True, text=True, timeout=20)
        s = (d.stdout or '').strip()
        if re.match(r'^\d{4}-\d{2}-\d{2}$', s):
            return s
    except Exception:
        pass
    return datetime.date.fromtimestamp(os.path.getmtime(os.path.join(ROOT, path))).isoformat()


def indexable(name):
    if name in SKIP:
        return False
    src = open(os.path.join(ROOT, name), encoding='utf-8').read()
    m = re.search(r'<meta\s+name="robots"[^>]*content="([^"]*)"', src, re.I)
    return not (m and 'noindex' in m.group(1).lower())


def homepage_images():
    src = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
    seen, out = set(), []
    for tag in re.findall(r'<img\b[^>]*>', src):
        s = re.search(r'\bsrc="([^"]+)"', tag)
        a = re.search(r'\balt="([^"]*)"', tag)
        if not s or not a or not a.group(1).strip():
            continue
        u = s.group(1)
        if 'logo' in u or u in seen:
            continue
        # A sitemap that lists a 404 is worse than one that lists nothing.
        if not os.path.isfile(os.path.join(ROOT, u)):
            sys.stderr.write('gen-sitemap: skipping missing image ' + u + chr(10))
            continue
        seen.add(u)
        out.append(u)
    return out


def loc(name, site):
    return site + '/' if name == 'index.html' else site + '/' + name


def build():
    site = site_origin()
    pages = sorted(f for f in os.listdir(ROOT)
                   if f.endswith('.html') and indexable(f))
    pages.sort(key=lambda f: (f != 'index.html', f))   # homepage first
    lines = [HEADER.rstrip('\n'),
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
             '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">']
    for f in pages:
        lines.append('  <url>')
        lines.append('    <loc>%s</loc>' % loc(f, site))
        lines.append('    <lastmod>%s</lastmod>' % git_date(f))
        if f == 'index.html':
            for img in homepage_images():
                lines.append('    <image:image><image:loc>%s/%s</image:loc></image:image>'
                             % (site, img))
        lines.append('  </url>')
    lines.append('</urlset>')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    new = build()
    if '--check' in sys.argv:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        # Compare ignoring the SITE_URL substitution, so --check still works
        # after tools/set-site-url.sh has rewritten the live file.
        norm = lambda s: re.sub(r'https?://[^/<]+', 'SITE_URL', s)
        if norm(cur) != norm(new):
            print('sitemap.xml is stale - run tools/gen-sitemap.py')
            sys.exit(1)
        print('sitemap.xml is current')
        sys.exit(0)
    open(OUT, 'w', encoding='utf-8').write(new)
    n = new.count('<url>')
    i = new.count('<image:image><image:loc>')
    print('sitemap.xml: %d url(s), %d image(s)' % (n, i))
